name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      # Add cache clearing step
      - name: Clear Cache
        run: |
          npm cache clean --force
          rm -rf .firebase
          rm -rf build
          rm -rf dist

      # Add step to ensure public directory exists
      - name: Create public directory
        run: mkdir -p public

      # Add step to copy static assets
      - name: Copy Static Assets
        run: |
          if exist "public" (
            xcopy /E /I /Y "public\*" "dist\"
          )
        shell: cmd

      - name: Build
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: "choice-center"
